services:
  mlflow:
    build:
      context: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mldata:/app

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: palantir
      MYSQL_DATABASE: palantir
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  palantir:
    build:
      context: ./palantir
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mlflow
    env_file:
      - .env

  ml_churn_app:
    build:
      context: ./examples/churn
    ports:
      - "5001:5001"
    depends_on:
      - mlflow
    env_file:
      - .env